package voicemenu.plugin.project.wizard;

/*Generated by MPS */

import jetbrains.mps.annotations.ResourceModule;
import jetbrains.mps.smodel.runtime.IconResource;

@ResourceModule("f5c3a3a7-38a1-4385-b73a-9993180f3701(voicemenu)")
public class IconContainer {
  protected static IconResource RESOURCE_0 = new IconResource("/icons/IVR_icon_16.png", null, IconContainer.class);
}
