package voicemenu.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ApplicationPluginPart;
import voicemenu.plugin.project.wizard.VoiceMenuProjectGroup;
import com.intellij.openapi.extensions.Extensions;
import jetbrains.mps.workbench.dialogs.project.newproject.ProjectTemplatesGroup;

public class VoiceMenu_AppPluginPart extends ApplicationPluginPart {
  private VoiceMenuProjectGroup voiceMenuProjectGroup = new VoiceMenuProjectGroup();
  public VoiceMenu_AppPluginPart() {
  }
  @Override
  public void init() {
    Extensions.getRootArea().getExtensionPoint(ProjectTemplatesGroup.EP_NAME).registerExtension(VoiceMenu_AppPluginPart.this.voiceMenuProjectGroup);

  }
  @Override
  public void dispose() {
    Extensions.getRootArea().getExtensionPoint(ProjectTemplatesGroup.EP_NAME).unregisterExtension(VoiceMenu_AppPluginPart.this.voiceMenuProjectGroup);
  }
}
