package jetbrains.mps.samples.VoiceMenu.sandbox;

/*Generated by MPS */

import java.awt.event.ActionListener;
import JavaVoiceMenu.runtime.Event;
import java.util.ArrayList;
import JavaVoiceMenu.runtime.Variables;
import JavaVoiceMenu.runtime.Behaviour;
import JavaVoiceMenu.runtime.Style;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import JavaVoiceMenu.runtime.Data;
import javax.swing.JButton;
import java.awt.Dimension;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;

public class Main__1 implements ActionListener {


  public static Main__1 instance;

  public static void initHashMap() {

    Event Home = new Event("myVoiceMenu", "0");
    Home.setAction("");
    Home.setGreeting("Welcome to our voicemenu");
    Home.childs = new ArrayList<Event>();
    Variables.main_Text = "myVoiceMenu";
    Variables.myHashMap.put("0", Home);


    Event _Internetu_35s59u_a0 = new Event("Internetu", "1");
    _Internetu_35s59u_a0.setAction("");
    _Internetu_35s59u_a0.setGreeting("");
    _Internetu_35s59u_a0.setGreeting("Welcome to the Internet");
    _Internetu_35s59u_a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Internetu_35s59u_a0.trigger;
    Variables.myHashMap.put(Variables.path, _Internetu_35s59u_a0);
    Event _Speed_up_35s59u_a0a0 = new Event("Speed up", "1");
    _Speed_up_35s59u_a0a0.setAction("");
    _Speed_up_35s59u_a0a0.setGreeting("");
    _Speed_up_35s59u_a0a0.setGreeting("Increasing speed was chosen");
    _Speed_up_35s59u_a0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Speed_up_35s59u_a0a0.trigger;
    Variables.myHashMap.put(Variables.path, _Speed_up_35s59u_a0a0);
    _Speed_up_35s59u_a0a0.setAction("getInfo");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Speed_up_35s59u_a0a0.childs = new ArrayList<Event>();
    Event _Discount_35s59u_b0a0 = new Event("Discount", "2");
    _Discount_35s59u_b0a0.setAction("");
    _Discount_35s59u_b0a0.setGreeting("");
    _Discount_35s59u_b0a0.setGreeting("Great choice!");
    _Discount_35s59u_b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Discount_35s59u_b0a0.trigger;
    Variables.myHashMap.put(Variables.path, _Discount_35s59u_b0a0);
    Event _Big_Discount_35s59u_b0b0a0 = new Event("Big Discount", "1");
    _Big_Discount_35s59u_b0b0a0.setAction("");
    _Big_Discount_35s59u_b0b0a0.setGreeting("");
    _Big_Discount_35s59u_b0b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Big_Discount_35s59u_b0b0a0.trigger;
    Variables.myHashMap.put(Variables.path, _Big_Discount_35s59u_b0b0a0);
    _Big_Discount_35s59u_b0b0a0.setAction("call");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Big_Discount_35s59u_b0b0a0.childs = new ArrayList<Event>();
    Event _Small_Discount_35s59u_a0b0a0 = new Event("Small Discount", "2");
    _Small_Discount_35s59u_a0b0a0.setAction("");
    _Small_Discount_35s59u_a0b0a0.setGreeting("");
    _Small_Discount_35s59u_a0b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Small_Discount_35s59u_a0b0a0.trigger;
    Variables.myHashMap.put(Variables.path, _Small_Discount_35s59u_a0b0a0);
    _Small_Discount_35s59u_a0b0a0.setAction("call");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Small_Discount_35s59u_a0b0a0.childs = new ArrayList<Event>();
    Event _Going_Back_35s59u_d0b0a0 = new Event("Going Back", "#");
    _Going_Back_35s59u_d0b0a0.setAction("");
    _Going_Back_35s59u_d0b0a0.setGreeting("");
    _Going_Back_35s59u_d0b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Going_Back_35s59u_d0b0a0.trigger;
    Variables.myHashMap.put(Variables.path, _Going_Back_35s59u_d0b0a0);
    _Going_Back_35s59u_d0b0a0.setAction("back");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Going_Back_35s59u_d0b0a0.childs = new ArrayList<Event>();
    Event _Going_Back_35s59u_c0b0a0 = new Event("Going Back", "*");
    _Going_Back_35s59u_c0b0a0.setAction("");
    _Going_Back_35s59u_c0b0a0.setGreeting("");
    _Going_Back_35s59u_c0b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Going_Back_35s59u_c0b0a0.trigger;
    Variables.myHashMap.put(Variables.path, _Going_Back_35s59u_c0b0a0);
    _Going_Back_35s59u_c0b0a0.setAction("back");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Going_Back_35s59u_c0b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Discount_35s59u_b0a0.childs = new ArrayList<Event>();
    _Discount_35s59u_b0a0.childs.add(_Small_Discount_35s59u_a0b0a0);
    _Discount_35s59u_b0a0.childs.add(_Big_Discount_35s59u_b0b0a0);
    _Discount_35s59u_b0a0.childs.add(_Going_Back_35s59u_c0b0a0);
    _Discount_35s59u_b0a0.childs.add(_Going_Back_35s59u_d0b0a0);
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Internetu_35s59u_a0.childs = new ArrayList<Event>();
    _Internetu_35s59u_a0.childs.add(_Speed_up_35s59u_a0a0);
    _Internetu_35s59u_a0.childs.add(_Discount_35s59u_b0a0);
    Event _Television_35s59u_b0 = new Event("Television", "2");
    _Television_35s59u_b0.setAction("");
    _Television_35s59u_b0.setGreeting("");
    _Television_35s59u_b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + _Television_35s59u_b0.trigger;
    Variables.myHashMap.put(Variables.path, _Television_35s59u_b0);
    _Television_35s59u_b0.setAction("getInfo");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    _Television_35s59u_b0.childs = new ArrayList<Event>();

    Home.childs.add(_Internetu_35s59u_a0);
    Home.childs.add(_Television_35s59u_b0);
  }

  public static void main(String[] args) {
    initHashMap();
    instance = new Main__1();
    Main__1.initHashMap();
    initView();
    Behaviour.runInitSetup();
  }

  public static void initView() {
    Style.setContent();
    addButtons(Style.myPanelOfButtons);
    Style.myPhone.add(Style.myPanelOfButtons, BorderLayout.SOUTH);
    Style.setFrame();
  }

  public static void addButtons(JPanel myPanelOfButtons) {
    for (Data.Status item : Data.Status.values()) {
      JButton button = new JButton(item.getCode());
      button.setActionCommand(item.getCode());
      button.addActionListener(instance);
      button.setPreferredSize(new Dimension(78, 76));
      Border border = new LineBorder(Color.white, 13);
      button.setBorder(border);
      myPanelOfButtons.add(button);
    }
  }
  @Override
  public void actionPerformed(ActionEvent event) {
    if (!(((Variables.path == null || Variables.path.length() == 0) || Variables.finished == true || Variables.started == false))) {
      try {
        Behaviour.runLogic(event);
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }

}
