package jetbrains.mps.samples.VoiceMenu.sandbox;

/*Generated by MPS */

import java.awt.event.ActionListener;
import JavaVoiceMenu.runtime.Event;
import java.util.ArrayList;
import JavaVoiceMenu.runtime.Variables;
import JavaVoiceMenu.runtime.Behaviour;
import JavaVoiceMenu.runtime.Style;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import JavaVoiceMenu.runtime.Data;
import javax.swing.JButton;
import java.awt.Dimension;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;

public class Main__1 implements ActionListener {


  public static Main__1 instance;

  public static void initHashMap() {

    Event Home = new Event("Jet-Mobile", "0");
    Home.setAction("");
    Home.setGreeting("Hello, welcome in Jet-Mobile");
    Home.childs = new ArrayList<Event>();
    Variables.main_Text = "Jet-Mobile";
    Variables.myHashMap.put("0", Home);


    Event Internet_m25aj_a0 = new Event("Internet", "1");
    Internet_m25aj_a0.setAction("");
    Internet_m25aj_a0.setGreeting("");
    Internet_m25aj_a0.setGreeting("Did you know that our internet is faster than ever?");
    Internet_m25aj_a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Internet_m25aj_a0.trigger;
    Variables.myHashMap.put(Variables.path, Internet_m25aj_a0);
    Event Discont_m25aj_a0a0 = new Event("Discont", "1");
    Discont_m25aj_a0a0.setAction("");
    Discont_m25aj_a0a0.setGreeting("");
    Discont_m25aj_a0a0.setGreeting("Welcome in section of discounts, here is everything cheaper.");
    Discont_m25aj_a0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Discont_m25aj_a0a0.trigger;
    Variables.myHashMap.put(Variables.path, Discont_m25aj_a0a0);
    Event Summer_discount_m25aj_a0a0a0 = new Event("Summer discount", "1");
    Summer_discount_m25aj_a0a0a0.setAction("");
    Summer_discount_m25aj_a0a0a0.setGreeting("");
    Summer_discount_m25aj_a0a0a0.setGreeting("Don't worry, while waiting you will listen your calm music.");
    Summer_discount_m25aj_a0a0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Summer_discount_m25aj_a0a0a0.trigger;
    Variables.myHashMap.put(Variables.path, Summer_discount_m25aj_a0a0a0);
    Summer_discount_m25aj_a0a0a0.setAction("call");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Summer_discount_m25aj_a0a0a0.childs = new ArrayList<Event>();
    Event Hidden_discounts_m25aj_b0a0a0 = new Event("Hidden discounts", "2");
    Hidden_discounts_m25aj_b0a0a0.setAction("");
    Hidden_discounts_m25aj_b0a0a0.setGreeting("");
    Hidden_discounts_m25aj_b0a0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Hidden_discounts_m25aj_b0a0a0.trigger;
    Variables.myHashMap.put(Variables.path, Hidden_discounts_m25aj_b0a0a0);
    Hidden_discounts_m25aj_b0a0a0.setAction("getInfo");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Hidden_discounts_m25aj_b0a0a0.childs = new ArrayList<Event>();
    Event Step_back_m25aj_c0a0a0 = new Event("Step back", "*");
    Step_back_m25aj_c0a0a0.setAction("");
    Step_back_m25aj_c0a0a0.setGreeting("");
    Step_back_m25aj_c0a0a0.setGreeting("Going back to the previous menu.");
    Step_back_m25aj_c0a0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Step_back_m25aj_c0a0a0.trigger;
    Variables.myHashMap.put(Variables.path, Step_back_m25aj_c0a0a0);
    Step_back_m25aj_c0a0a0.setAction("back");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Step_back_m25aj_c0a0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Discont_m25aj_a0a0.childs = new ArrayList<Event>();
    Discont_m25aj_a0a0.childs.add(Summer_discount_m25aj_a0a0a0);
    Discont_m25aj_a0a0.childs.add(Hidden_discounts_m25aj_b0a0a0);
    Discont_m25aj_a0a0.childs.add(Step_back_m25aj_c0a0a0);
    Event Data_limit_m25aj_b0a0 = new Event("Data limit", "2");
    Data_limit_m25aj_b0a0.setAction("");
    Data_limit_m25aj_b0a0.setGreeting("");
    Data_limit_m25aj_b0a0.setGreeting("Take care this call will be monitored.");
    Data_limit_m25aj_b0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Data_limit_m25aj_b0a0.trigger;
    Variables.myHashMap.put(Variables.path, Data_limit_m25aj_b0a0);
    Data_limit_m25aj_b0a0.setAction("call");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Data_limit_m25aj_b0a0.childs = new ArrayList<Event>();
    Event Return_to_main_menu_m25aj_c0a0 = new Event("Return to main menu", "*");
    Return_to_main_menu_m25aj_c0a0.setAction("");
    Return_to_main_menu_m25aj_c0a0.setGreeting("");
    Return_to_main_menu_m25aj_c0a0.setGreeting("Going back to the previous menu.");
    Return_to_main_menu_m25aj_c0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Return_to_main_menu_m25aj_c0a0.trigger;
    Variables.myHashMap.put(Variables.path, Return_to_main_menu_m25aj_c0a0);
    Return_to_main_menu_m25aj_c0a0.setAction("back");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Return_to_main_menu_m25aj_c0a0.childs = new ArrayList<Event>();
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Internet_m25aj_a0.childs = new ArrayList<Event>();
    Internet_m25aj_a0.childs.add(Discont_m25aj_a0a0);
    Internet_m25aj_a0.childs.add(Data_limit_m25aj_b0a0);
    Internet_m25aj_a0.childs.add(Return_to_main_menu_m25aj_c0a0);
    Event Payment_m25aj_b0 = new Event("Payment", "2");
    Payment_m25aj_b0.setAction("");
    Payment_m25aj_b0.setGreeting("");
    Payment_m25aj_b0.setGreeting("Since now we offer you easiest way of payment.");
    Payment_m25aj_b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Payment_m25aj_b0.trigger;
    Variables.myHashMap.put(Variables.path, Payment_m25aj_b0);
    Event Billing_m25aj_a0b0 = new Event("Billing", "1");
    Billing_m25aj_a0b0.setAction("");
    Billing_m25aj_a0b0.setGreeting("");
    Billing_m25aj_a0b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Billing_m25aj_a0b0.trigger;
    Variables.myHashMap.put(Variables.path, Billing_m25aj_a0b0);
    Billing_m25aj_a0b0.setAction("other");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Billing_m25aj_a0b0.childs = new ArrayList<Event>();
    Event Recharging_m25aj_b0b0 = new Event("Recharging", "2");
    Recharging_m25aj_b0b0.setAction("");
    Recharging_m25aj_b0b0.setGreeting("");
    Recharging_m25aj_b0b0.setGreeting("Now we are sending you super secret informations.");
    Recharging_m25aj_b0b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Recharging_m25aj_b0b0.trigger;
    Variables.myHashMap.put(Variables.path, Recharging_m25aj_b0b0);
    Recharging_m25aj_b0b0.setAction("getInfo");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Recharging_m25aj_b0b0.childs = new ArrayList<Event>();
    Event Payments_m25aj_c0b0 = new Event("Payments", "3");
    Payments_m25aj_c0b0.setAction("");
    Payments_m25aj_c0b0.setGreeting("");
    Payments_m25aj_c0b0.setGreeting("Connecting you with a human.");
    Payments_m25aj_c0b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Payments_m25aj_c0b0.trigger;
    Variables.myHashMap.put(Variables.path, Payments_m25aj_c0b0);
    Payments_m25aj_c0b0.setAction("call");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Payments_m25aj_c0b0.childs = new ArrayList<Event>();
    Event Step_back_m25aj_d0b0 = new Event("Step back", "*");
    Step_back_m25aj_d0b0.setAction("");
    Step_back_m25aj_d0b0.setGreeting("");
    Step_back_m25aj_d0b0.setGreeting("Going back to the previous menu.");
    Step_back_m25aj_d0b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Step_back_m25aj_d0b0.trigger;
    Variables.myHashMap.put(Variables.path, Step_back_m25aj_d0b0);
    Step_back_m25aj_d0b0.setAction("back");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Step_back_m25aj_d0b0.childs = new ArrayList<Event>();
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Payment_m25aj_b0.childs = new ArrayList<Event>();
    Payment_m25aj_b0.childs.add(Billing_m25aj_a0b0);
    Payment_m25aj_b0.childs.add(Recharging_m25aj_b0b0);
    Payment_m25aj_b0.childs.add(Payments_m25aj_c0b0);
    Payment_m25aj_b0.childs.add(Step_back_m25aj_d0b0);
    Event Roaming_m25aj_c0 = new Event("Roaming", "3");
    Roaming_m25aj_c0.setAction("");
    Roaming_m25aj_c0.setGreeting("");
    Roaming_m25aj_c0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Roaming_m25aj_c0.trigger;
    Variables.myHashMap.put(Variables.path, Roaming_m25aj_c0);
    Roaming_m25aj_c0.setAction("getInfo");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Roaming_m25aj_c0.childs = new ArrayList<Event>();
    Event News_m25aj_d0 = new Event("News", "4");
    News_m25aj_d0.setAction("");
    News_m25aj_d0.setGreeting("");
    News_m25aj_d0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + News_m25aj_d0.trigger;
    Variables.myHashMap.put(Variables.path, News_m25aj_d0);
    Event Summer_News_m25aj_a0d0 = new Event("Summer News", "1");
    Summer_News_m25aj_a0d0.setAction("");
    Summer_News_m25aj_a0d0.setGreeting("");
    Summer_News_m25aj_a0d0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Summer_News_m25aj_a0d0.trigger;
    Variables.myHashMap.put(Variables.path, Summer_News_m25aj_a0d0);
    Summer_News_m25aj_a0d0.setAction("call");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Summer_News_m25aj_a0d0.childs = new ArrayList<Event>();
    Event Cold_News_m25aj_b0d0 = new Event("Cold News", "2");
    Cold_News_m25aj_b0d0.setAction("");
    Cold_News_m25aj_b0d0.setGreeting("");
    Cold_News_m25aj_b0d0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Cold_News_m25aj_b0d0.trigger;
    Variables.myHashMap.put(Variables.path, Cold_News_m25aj_b0d0);
    Cold_News_m25aj_b0d0.setAction("getInfo");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Cold_News_m25aj_b0d0.childs = new ArrayList<Event>();
    Event Step_Back_m25aj_c0d0 = new Event("Step Back", "3");
    Step_Back_m25aj_c0d0.setAction("");
    Step_Back_m25aj_c0d0.setGreeting("");
    Step_Back_m25aj_c0d0.setGreeting("Going back to the previous menu.");
    Step_Back_m25aj_c0d0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Step_Back_m25aj_c0d0.trigger;
    Variables.myHashMap.put(Variables.path, Step_Back_m25aj_c0d0);
    Step_Back_m25aj_c0d0.setAction("back");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Step_Back_m25aj_c0d0.childs = new ArrayList<Event>();
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    News_m25aj_d0.childs = new ArrayList<Event>();
    News_m25aj_d0.childs.add(Summer_News_m25aj_a0d0);
    News_m25aj_d0.childs.add(Cold_News_m25aj_b0d0);
    News_m25aj_d0.childs.add(Step_Back_m25aj_c0d0);
    Event Other_requirements_m25aj_e0 = new Event("Other requirements", "5");
    Other_requirements_m25aj_e0.setAction("");
    Other_requirements_m25aj_e0.setGreeting("");
    Other_requirements_m25aj_e0.childs = new ArrayList<Event>();
    Variables.path = Variables.path + Other_requirements_m25aj_e0.trigger;
    Variables.myHashMap.put(Variables.path, Other_requirements_m25aj_e0);
    Other_requirements_m25aj_e0.setAction("other");
    Variables.path = Variables.path.substring(0, Variables.path.length() - 1);
    Other_requirements_m25aj_e0.childs = new ArrayList<Event>();

    Home.childs.add(Internet_m25aj_a0);
    Home.childs.add(Payment_m25aj_b0);
    Home.childs.add(Roaming_m25aj_c0);
    Home.childs.add(News_m25aj_d0);
    Home.childs.add(Other_requirements_m25aj_e0);
  }

  public static void main(String[] args) {
    initHashMap();
    instance = new Main__1();
    Main__1.initHashMap();
    initView();
    Behaviour.runInitSetup();
  }

  public static void initView() {
    Style.setContent();
    addButtons(Style.myPanelOfButtons);
    Style.myPhone.add(Style.myPanelOfButtons, BorderLayout.SOUTH);
    Style.setFrame();
  }

  public static void addButtons(JPanel myPanelOfButtons) {
    for (Data.Status item : Data.Status.values()) {
      JButton button = new JButton(item.getCode());
      button.setActionCommand(item.getCode());
      button.addActionListener(instance);
      button.setPreferredSize(new Dimension(78, 76));
      Border border = new LineBorder(Color.white, 13);
      button.setBorder(border);
      myPanelOfButtons.add(button);
    }
  }
  @Override
  public void actionPerformed(ActionEvent event) {
    if (!(((Variables.path == null || Variables.path.length() == 0) || Variables.finished == true))) {
      try {
        Behaviour.runLogic(event);
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }

}
