package jetbrains.mps.samples.VoiceMenu.sandbox;

/*Generated by MPS */

import java.awt.event.ActionListener;
import JavaVoiceMenu.runtime.Event;
import java.util.ArrayList;
import JavaVoiceMenu.runtime.Variables;
import JavaVoiceMenu.runtime.Behaviour;
import JavaVoiceMenu.runtime.Style;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import JavaVoiceMenu.runtime.Data;
import javax.swing.JButton;
import java.awt.Dimension;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;

public class Main__4 implements ActionListener {


  public static Main__4 instance;

  public static void initHashMap() {

    Event Home = new Event("Test2", "0", 8);
    Home.setAction("", true);
    Home.setGreeting("");
    Home.childs = new ArrayList<Event>();
    Home.isFinal = false;
    Variables.main_Text = "Test2";

    Variables.myHashMap.put("0", Home);


    Event timeout_o0tsw_c0 = new Event("timeout", "X", 16);
    timeout_o0tsw_c0.isFinal = false;
    timeout_o0tsw_c0.setAction("", false);
    timeout_o0tsw_c0.setGreeting("");
    timeout_o0tsw_c0.childs = new ArrayList<Event>();
    Variables.myHashMap.put("0X", timeout_o0tsw_c0);
    timeout_o0tsw_c0.setAction("repeat", false);
    timeout_o0tsw_c0.childs = new ArrayList<Event>();
    Event Get_Info_o0tsw_a0 = new Event("Get Info", "1", 16);
    Get_Info_o0tsw_a0.isFinal = false;
    Get_Info_o0tsw_a0.setAction("", false);
    Get_Info_o0tsw_a0.setGreeting("");
    Get_Info_o0tsw_a0.childs = new ArrayList<Event>();
    Variables.myHashMap.put("01", Get_Info_o0tsw_a0);
    Get_Info_o0tsw_a0.setAction("getInfo", false);
    Get_Info_o0tsw_a0.childs = new ArrayList<Event>();
    Event Menu_o0tsw_b0 = new Event("Menu", "2", 16);
    Menu_o0tsw_b0.isFinal = false;
    Menu_o0tsw_b0.setAction("", false);
    Menu_o0tsw_b0.setGreeting("");
    Menu_o0tsw_b0.childs = new ArrayList<Event>();
    Variables.myHashMap.put("02", Menu_o0tsw_b0);
    Event Timeout_o0tsw_c0c0 = new Event("Timeout", "X", 16);
    Timeout_o0tsw_c0c0.isFinal = false;
    Timeout_o0tsw_c0c0.setAction("", false);
    Timeout_o0tsw_c0c0.setGreeting("");
    Timeout_o0tsw_c0c0.childs = new ArrayList<Event>();
    Variables.myHashMap.put("02X", Timeout_o0tsw_c0c0);
    Timeout_o0tsw_c0c0.setAction("repeat", false);
    Timeout_o0tsw_c0c0.childs = new ArrayList<Event>();
    Event HangUp_o0tsw_a0c0 = new Event("HangUp", "1", 16);
    HangUp_o0tsw_a0c0.isFinal = false;
    HangUp_o0tsw_a0c0.setAction("", false);
    HangUp_o0tsw_a0c0.setGreeting("");
    HangUp_o0tsw_a0c0.childs = new ArrayList<Event>();
    Variables.myHashMap.put("021", HangUp_o0tsw_a0c0);
    HangUp_o0tsw_a0c0.setAction("hangUp", true);
    HangUp_o0tsw_a0c0.childs = new ArrayList<Event>();
    Event GetInfo_o0tsw_b0c0 = new Event("GetInfo", "2", 16);
    GetInfo_o0tsw_b0c0.isFinal = false;
    GetInfo_o0tsw_b0c0.setAction("", false);
    GetInfo_o0tsw_b0c0.setGreeting("");
    GetInfo_o0tsw_b0c0.childs = new ArrayList<Event>();
    Variables.myHashMap.put("022", GetInfo_o0tsw_b0c0);
    GetInfo_o0tsw_b0c0.setAction("getInfo", false);
    GetInfo_o0tsw_b0c0.childs = new ArrayList<Event>();
    Menu_o0tsw_b0.childs = new ArrayList<Event>();
    Menu_o0tsw_b0.childs.add(HangUp_o0tsw_a0c0);
    Menu_o0tsw_b0.childs.add(GetInfo_o0tsw_b0c0);

    Home.childs.add(Get_Info_o0tsw_a0);
    Home.childs.add(Menu_o0tsw_b0);
  }

  public static void main(String[] args) {
    initHashMap();
    instance = new Main__4();
    Main__4.initHashMap();
    initView();
    Behaviour.runInitSetup();
    (Variables.timerThr = new Thread(new Behaviour.myTimer(null, true, 13))).start();

  }

  public static void initView() {
    Style.setContent();
    addButtons(Style.myPanelOfButtons);
    Style.myPhone.add(Style.myPanelOfButtons, BorderLayout.SOUTH);
    Style.setFrame();
  }

  public static void addButtons(JPanel myPanelOfButtons) {
    for (Data.Status item : Data.Status.values()) {
      JButton button = new JButton(item.getCode());
      button.setActionCommand(item.getCode());
      button.addActionListener(instance);
      button.setPreferredSize(new Dimension(78, 76));
      Border border = new LineBorder(Color.white, 13);
      button.setBorder(border);
      myPanelOfButtons.add(button);
    }
  }
  @Override
  public void actionPerformed(ActionEvent event) {
    if (!(((Variables.path == null || Variables.path.length() == 0) || Variables.finished == true || Variables.started == false))) {
      try {
        if (Variables.timerThr.isAlive()) {
          Variables.timerThr.interrupt();
        }
        Behaviour.runLogic(event, false);

      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }

}
