package jetbrains.mps.samples.VoiceMenu.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {



}
