package jetbrains.mps.samples.VoiceMenu.editor;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a9c6h = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8h = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6j = new IconResource("phone.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7j = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8j = new IconResource("menu.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c9j = new IconResource("info.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c01j = new IconResource("donkey.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01e6g9 = new IconResource("button_click.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c6k = new IconResource("random.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6l = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7l = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8l = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a01c9l = new IconResource("plus.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_0 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h_0 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8h_0 = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6i = new IconResource("phone.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7i = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8i = new IconResource("menu.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c9i = new IconResource("info.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_1 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h_1 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8h_1 = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6i_0 = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7i_0 = new IconResource("menu.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8i_0 = new IconResource("info.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c9i_0 = new IconResource("donkey.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_2 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h_2 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8h_2 = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6i_1 = new IconResource("phone.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7i_1 = new IconResource("menu.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8i_1 = new IconResource("info.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c9i_1 = new IconResource("donkey.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_3 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h_3 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8h_3 = new IconResource("remove.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6i_2 = new IconResource("phone.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7i_2 = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8i_2 = new IconResource("menu.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c9i_2 = new IconResource("donkey.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_4 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h_4 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6i_3 = new IconResource("phone.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7i_3 = new IconResource("arrow.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8i_3 = new IconResource("info.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c9i_3 = new IconResource("donkey.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c6h_5 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c7h_5 = new IconResource("add_to_list.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a9c8h_4 = new IconResource("remove.png", IconContainer.class);
}
